<?php
// Variables
return [
  "creatorName" => "ThemeSelection",
  "creatorUrl" => "https://themeselection.com",
  "templateName" => "MySalam Online",
  "templateSuffix" => "Buy Policies Online",
  "templateVersion" => "1.0.0",
  "templateFree" => true,
  "templateDescription" => "Salam Takaful Online Agent Sales platform. ",
  "templateKeyword" => "laravel 12, bootstrap 5, bootstrap 5",
  "licenseUrl" => "https://themeselection.com/license/",
  "livePreview" => "#",
  "productPage" => "https://themeselection.com/item/sneat-free-bootstrap-laravel-livewire-starter-kit/",
  "ogTitle" => "MySalam Online -Buy Policies Online",
  "ogType" => "product",
  "ogImage" => "https://github-production-user-asset-6210df.s3.amazonaws.com/61959920/427962312-a4f2c59c-92a0-4624-a0f0-d53ee0acf7d9.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVCODYLSA53PQK4ZA%2F20250328%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250328T104541Z&X-Amz-Expires=300&X-Amz-Signature=88f19338f62219496631c44f4da216a3f2da10169fb75377cdc9146dc1722352&X-Amz-SignedHeaders=host",
  "support" => "https://github.com/themeselection/sneat-bootstrap-laravel-livewire-starter-kit/issues",
  "moreThemes" => "#",
  "documentation" => "#",
  "repository" => "#",
  "gitRepo" => "#",
  "gitRepoAccess" => "#",
  "githubFreeUrl" => "https://github.com/",
  "facebookUrl" => "https://www.facebook.com/",
  "twitterUrl" => "https://x.com/",
  "githubUrl" => "https://github.com/",
  "dribbbleUrl" => "https://dribbble.com/",
  "instagramUrl" => "https://www.instagram.com/",
  "API_ELITE_TOKEN" =>env('API_ELITE_TOKEN'), //default agent token
  "API_ELITE_URL"=>env('API_ELITE_URL'),
  "NIIP_URL" => env('NIIP_URL'),
  "NIIP_API_KEY" => env('NIIP_API_KEY'), // niip token
  "NIID_URL" => env('NIID_URL'),
  "NIID_USERNAME" => env('NIID_USERNAME'),
  "NIID_PASSWORD" => env('NIID_PASSWORD'),

  "PROXY_URL"    => env('PROXY_URL', ''),
  "PROXY_SECRET" => env('PROXY_SECRET', ''),
  "CLAIMS_EMAIL"     => env('CLAIMS_EMAIL',     'claims@salamtakafulinsurance.com'),
  "TECHNICAL_EMAIL"  => env('TECHNICAL_EMAIL',  'technical@salamtakafulinsurance.com'),
];
